- name: "Playbook for {{ component }} Configuration"
  hosts: localhost
  connection: local
  become: true
  vars_files:
    - credentials.yaml
    - variables-{{env}}.yaml
  roles:
    - "{{ component }}"
